/*******************************************************************************
 * DARPA XDATA licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with 
 * the License.  You may obtain a copy of the License at 
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and  
 * limitations under the License.
 * 
 * Copyright 2013 Raytheon BBN Technologies Corp. All Rights Reserved.
 ******************************************************************************/
/* =============================================================================
 *
 *                  COPYRIGHT 2010 BBN Technologies Corp.
 *                  1300 North 17th Street, Suite 600
 *                       Arlington, VA  22209
 *                          (703) 284-1200
 *
 *       This program is the subject of intellectual property rights
 *       licensed from BBN Technologies
 *
 *       This legend must continue to appear in the source code
 *       despite modifications or enhancements by any party.
 *
 *
 * ==============================================================================
 */
package com.bbn.c2s2.pint.vocab;

import com.hp.hpl.jena.rdf.model.Model;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Property;
import com.hp.hpl.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from C:Documents and SettingskrohloffMy
 * DocumentsBBNJHU-APLpint-repo/data/rdf/RNRM.rdf
 * 
 * @author Auto-generated by schemagen on 15 Jan 2010 18:05
 */
public class RNRM {
	/**
	 * <p>
	 * The RDF model that holds the vocabulary terms
	 * </p>
	 */
	private static Model m_model = ModelFactory.createDefaultModel();

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 */
	public static final String NS = "http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#";

	/**
	 * <p>
	 * The namespace of the vocabulary as a string
	 * </p>
	 * 
	 * @see #NS
	 */
	public static String getURI() {
		return NS;
	}

	/**
	 * <p>
	 * The namespace of the vocabulary as a resource
	 * </p>
	 */
	public static final Resource NAMESPACE = m_model.createResource(NS);

	public static final Property containedBy = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#containedBy");

	public static final Property contains = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#contains");

	public static final Property hasAltitude = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasAltitude");

	public static final Property hasChildProcess = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasChildProcess");

	public static final Property hasCreationDatetime = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasCreationDatetime");

	public static final Property hasCreator = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasCreator");

	public static final Property hasElement = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasElement");

	public static final Property hasEndElement = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasEndElement");

	public static final Property hasFileType = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasFileType");

	public static final Property hasFileUrl = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasFileUrl");

	public static final Property hasFunctionalArea = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasFunctionalArea");

	public static final Property hasGeocode = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasGeocode");

	public static final Property hasIntelligenceDiscipline = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasIntelligenceDiscipline");

	public static final Property hasLatitude = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasLatitude");

	public static final Property hasLongitude = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasLongitude");

	public static final Property hasMaxDuration = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasMaxDuration");

	public static final Property hasMedia = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasMedia");

	public static final Property hasMinDuration = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasMinDuration");

	public static final Property hasObservable = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasObservable");

	public static final Property hasObservationDatetime = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasObservationDatetime");

	public static final Property hasOriginatingSource = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasOriginatingSource");

	public static final Property hasOrsaTrend = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasOrsaTrend");

	public static final Property hasParentProcess = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasParentProcess");

	public static final Property hasSqlId = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasSqlId");

	public static final Property hasStartElement = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasStartElement");

	public static final Property hasTrend = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#hasTrend");

	public static final Property isElementOf = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isElementOf");

	public static final Property isEndElementOf = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isEndElementOf");

	public static final Property isFlowingTo = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isFlowingTo");

	public static final Property isInformationFlowingTo = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isInformationFlowingTo");

	public static final Property isMaterialFlowingTo = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isMaterialFlowingTo");

	public static final Property isMoneyFlowingTo = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isMoneyFlowingTo");

	public static final Property isObservationOf = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isObservationOf");

	public static final Property isObservedBy = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isObservedBy");

	public static final Property isPersonnelFlowingTo = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isPersonnelFlowingTo");

	/**
	 * <p>
	 * Use this property to indicate ActivityElements that represent an
	 * Activity.
	 * </p>
	 */
	public static final Property isRepresentedByActivityElement = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isRepresentedByActivityElement");

	public static final Property isStartElementOf = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isStartElementOf");

	public static final Property isTargetsFlowingTo = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#isTargetsFlowingTo");

	/**
	 * <p>
	 * Use this property to indicate the Activity represented by an
	 * ActivityElement.
	 * </p>
	 */
	public static final Property representsActivity = m_model
			.createProperty("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#representsActivity");

	public static final Resource Activity = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Activity");

	public static final Resource ActivityElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#ActivityElement");

	public static final Resource ChildProcess = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#ChildProcess");

	public static final Resource DecisionElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#DecisionElement");

	public static final Resource EndStateElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#EndStateElement");

	public static final Resource ForkElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#ForkElement");

	public static final Resource FunctionalArea = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#FunctionalArea");

	public static final Resource GeoTrend = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#GeoTrend");

	public static final Resource Geocode = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Geocode");

	public static final Resource IntelligenceDiscipline = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#IntelligenceDiscipline");

	public static final Resource IntelligenceSubDiscipline = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#IntelligenceSubDiscipline");

	public static final Resource JoinElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#JoinElement");

	public static final Resource Media = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Media");

	public static final Resource MergeElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#MergeElement");

	public static final Resource Observable = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Observable");

	public static final Resource Observation = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Observation");

	public static final Resource OracleImport = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#OracleImport");

	public static final Resource ParentProcess = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#ParentProcess");

	public static final Resource Process = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Process");

	public static final Resource ProcessElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#ProcessElement");

	public static final Resource Provenance = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Provenance");

	public static final Resource RedNode = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#RedNode");

	public static final Resource SocioTrend = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#SocioTrend");

	public static final Resource StartStateElement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#StartStateElement");

	public static final Resource SubProcess = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#SubProcess");

	public static final Resource SuperProcess = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#SuperProcess");

	public static final Resource Trend = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Trend");

	public static final Resource AdaptationResearchAndDevelopment = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#AdaptationResearchAndDevelopment");

	public static final Resource Assessment = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Assessment");

	public static final Resource CI = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#CI");

	public static final Resource COMINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#COMINT");

	public static final Resource ComponentSupply = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#ComponentSupply");

	public static final Resource DetectAndDetonate = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#DetectAndDetonate");

	public static final Resource DomesticSupport = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#DomesticSupport");

	public static final Resource Egress = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Egress");

	public static final Resource Emplacement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Emplacement");

	public static final Resource Execute = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Execute");

	public static final Resource GEOINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#GEOINT");

	public static final Resource HUMINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#HUMINT");

	public static final Resource IEDManufacturing = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#IEDManufacturing");

	public static final Resource IMINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#IMINT");

	public static final Resource Ingress = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Ingress");

	public static final Resource InternationalSupport = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#InternationalSupport");

	public static final Resource Inventory = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Inventory");

	public static final Resource Leadership = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Leadership");

	public static final Resource LocalLeadership = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#LocalLeadership");

	public static final Resource MASINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#MASINT");

	public static final Resource MonitorAndArm = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#MonitorAndArm");

	public static final Resource NationalAndRegionalLeadership = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#NationalAndRegionalLeadership");

	public static final Resource OSINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#OSINT");

	public static final Resource Observe = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Observe");

	public static final Resource Planning = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Planning");

	public static final Resource PostDetonationIO = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#PostDetonationIO");

	public static final Resource Procurement = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Procurement");

	public static final Resource Recruiting = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Recruiting");

	public static final Resource SIGINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#SIGINT");

	public static final Resource Storage = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Storage");

	public static final Resource SupplyChain = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#SupplyChain");

	public static final Resource Support = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Support");

	public static final Resource Surveillance = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Surveillance");

	public static final Resource TECHINT = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#TECHINT");

	public static final Resource Training = m_model
			.createResource("http://www.c2s2.jhuapl.edu/2009/04/30/rnrm#Training");

}
